{{- /* To test this krew-release-bot template before committing it:
  # Replace 0.6.1 below with the current kube-capacity version.
  # Replace 0.0.40 below with the current version of the krew-release-bot used
  # in the .circleci/config.yml file.
  $ docker run -v `pwd`/.krew.yaml:/tmp/template.yaml rajatjindal/krew-release-bot:v0.0.40 krew-release-bot template --tag 0.6.1 --template-file /tmp/template.yaml >dist/krew.yaml
  # Use krew to install via the krew manifest created above:
  $ kubectl krew install --manifest=dist/krew.yaml 
  # Alternatively, test krew downloading different OS and architecture combinations with:
  $ KREW_OS=windows KREW_ARCH=amd64 kubectl krew install --manifest=dist/krew.yaml
*/ -}}
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: resource-capacity
spec:
  version: v{{ .TagName }}
  homepage: https://github.com/robscott/kube-capacity
  shortDescription: Provides an overview of resource requests, limits, and utilization
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    bin: kube-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/robscott/kube-capacity/releases/download/v{{ .TagName }}/kube-capacity_{{ .TagName }}_Darwin_x86_64.tar.gz" .TagName }}    
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    bin: kube-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/robscott/kube-capacity/releases/download/v{{ .TagName }}/kube-capacity_{{ .TagName }}_Darwin_arm64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    bin: kube-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/robscott/kube-capacity/releases/download/v{{ .TagName }}/kube-capacity_{{ .TagName }}_Linux_x86_64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    bin: kube-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/robscott/kube-capacity/releases/download/v{{ .TagName }}/kube-capacity_{{ .TagName }}_Linux_arm64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    bin: kube-capacity.exe
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/robscott/kube-capacity/releases/download/v{{ .TagName }}/kube-capacity_{{ .TagName }}_Windows_x86_64.tar.gz" .TagName }}
  description: |
    A simple CLI that provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster.
